# Generated by Django 3.1.7 on 2021-07-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210706_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(default='gupshup/media/default2.png', max_length=200),
        ),
    ]
