# Generated by Django 3.1.7 on 2021-07-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210706_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='gupshup/media/default2.png'),
        ),
    ]
