# Generated by Django 3.1.7 on 2021-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210706_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, choices=[('KJSCE', 'KSCE'), ('Aurobindo', 'Aurobindo'), ('Chanakya', 'Chanakya')], default='KJSCE', max_length=20, null=True),
        ),
    ]
