# Generated by Django 3.1.7 on 2021-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210731_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default2_rl6g0r.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/hqdqbozua/image/upload/v1628252659/media/default2_rl6g0r.png'),
        ),
    ]
