# Generated by Django 3.1.7 on 2021-03-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_num_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_likes',
        ),
    ]
