# Generated by Django 3.1.7 on 2021-03-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_num_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='content',
            new_name='comment',
        ),
    ]
