# Generated by Django 3.1.7 on 2021-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Mechanical', 'Mechanical'), ('Electronic', 'Electronic'), ('Sports', 'Sports'), ('Business', 'Business'), ('Announcments', 'Announcments'), ('Cultural', 'Cultural'), ('Politics', 'Politics'), ('Health', 'Health'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Miscellenous', 'Miscellenous')], default='Miscellenous', max_length=20),
        ),
    ]
