# Generated by Django 3.1.7 on 2021-07-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_appropriate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='notice',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
