# Generated by Django 3.1.7 on 2021-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210712_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='notice',
            field=models.CharField(blank=True, default='This Post was DELETED', max_length=100, null=True),
        ),
    ]
