# Generated by Django 3.1.7 on 2021-07-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210730_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='num_of_posts',
            field=models.IntegerField(default=0),
        ),
    ]
