# Generated by Django 3.1.7 on 2021-07-07 09:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210707_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, choices=[('KJSCE', 'KJSCE'), ('Aurobindo', 'Aurobindo'), ('Chanakya', 'Chanakya')], default='KJSCE', max_length=20, null=True),
        ),
    ]
