# Generated by Django 3.1.7 on 2021-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210730_1602'),
        ('users', '0012_profile_followed_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_category', to='blog.Category'),
        ),
    ]
